### ISSUE TITLE
Install Instructions? Missing Files?

### ISSUE THREAD

**Issue by epl692** [aiju/jsdrawterm#3]
Is this still a viable project, and if so, how would one start to install this on there plan9 system?

**Comment by aiju** [comment]
It was never completed and it was never meant to run on Plan 9. wsproxy.go runs on a *nix system (not sure about current Go support on Plan 9). The *.js files are then run in a web browser that lets you log into the Plan 9 system wsproxy.go is set up to connect to.
devdraw support is virtually nonexistent.
The new dp9ik auth protocol is not supported either. (It postdates my efforts)
If someone wants to finish the code, they can of course feel free to do that and I'll be happy to help but I have no plans to do it myself, sorry.

**Comment by epl692** [comment]
Okay, was just wondering what the status of this was. Thank you.
